name: Build and Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker southamerica-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t southamerica-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/alura-imersao-devops:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push southamerica-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/alura-imersao-devops:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy alura-imersao-devops \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/alura-imersao-devops:${{ github.sha }} \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated
